pipeline:
  name: echo hello
  identifier: echo_hello
  projectIdentifier: pipelinetest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test stage
        identifier: Test_stage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "test"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
